//
//  LanguageAlertViewController.swift
//  Noty
//
//  Created by Youssef Jdidi on 24/3/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol LanguageAlertViewControllerProtocol: class, UIViewControllerRouting {
    func set(interactor: LanguageAlertInteractorProtocol)
    func set(router: LanguageAlertRouterProtocol)

    // add the functions that are called from the presenter
    func display(error: Error)
}

class LanguageAlertViewController: UIViewController, LanguageAlertViewControllerProtocol {

    // MARK: DI
    var interactor: LanguageAlertInteractorProtocol?
    var router: LanguageAlertRouterProtocol?

    func set(interactor: LanguageAlertInteractorProtocol) {
        self.interactor = interactor
    }

    func set(router: LanguageAlertRouterProtocol) {
        self.router = router
    }
    

    // MARK: Outlets

    // MARK: Properties

    // MARK: Lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
    }

    // MARK: Actions

}

// MARK: Methods
extension LanguageAlertViewController {

    func display(error: Error) {}
}
