//
//  LanguageAlertInteractor.swift
//  Noty
//
//  Created by Youssef Jdidi on 24/3/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol LanguageAlertInteractorProtocol {
    func handleInitialLanguage()
    func handleSavingLanguage(language: Locale)
}

class LanguageAlertInteractor: LanguageAlertInteractorProtocol {

    // MARK: DI
    var presenter: LanguageAlertPresenterProtocol
    var userDefaults: UserDefaultsManagerProtocol

    init(
        presenter: LanguageAlertPresenterProtocol,
        userDefaults: UserDefaultsManagerProtocol
    ) {
        self.presenter = presenter
        self.userDefaults = userDefaults
    }
}

extension LanguageAlertInteractor {
    func handleInitialLanguage() {
        presenter.present(initial: userDefaults.selectedLanguage)
    }

    func handleSavingLanguage(language: Locale) {
        userDefaults.selectedLanguage = language
        presenter.presentSaving()
    }
}
