//
//  HomePresenter.swift
//  Noty
//
//  Created by Youssef Jdidi on 12/2/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol HomePresenterProtocol {
    func set(viewController: HomeViewControllerProtocol?)

    // add the functions that are called from interactor
    func handle(error: Error)
    func presentPermissionError(error: HomeModels.PermissionError)
    func presentTranscripted(transcripted text: String)
    func presentRecordingState(_ state: HomeModels.RecordState)
    func presentCurrentAmplitude(with amplitude: Double)
    func present(actionSheet: UIAlertController)
    func present(choiceActionSheet: UIAlertController)
    func presentSpinner()
    func present(save result: Result<Storable?, Error>)
    func presentRoutingToTitle()
}

class HomePresenter: HomePresenterProtocol {

    // MARK: DI
    weak var viewController: HomeViewControllerProtocol?

    func set(viewController: HomeViewControllerProtocol?) {
        self.viewController = viewController
    }
}

// MARK: Methods
extension  HomePresenter {

    func handle(error: Error) {
        viewController?.display(error: error)
    }

    func presentPermissionError(error: HomeModels.PermissionError) {
        viewController?.displayPermissionError(error: error)
    }

    func presentTranscripted(transcripted text: String) {
        viewController?.displayTranscriptedText(text: text)
    }

    func presentRecordingState(_ state: HomeModels.RecordState) {
        viewController?.displayRecordingState(state: state)
    }

    func presentCurrentAmplitude(with amplitude: Double) {
        viewController?.displayCurrentAmplitude(with: amplitude)
    }

    func present(actionSheet: UIAlertController) {
        viewController?.displayActionSheet(actionSheet: actionSheet)
    }

    func present(choiceActionSheet: UIAlertController) {
        viewController?.display(choiceActionSheet: choiceActionSheet)
    }

    func presentSpinner() {
        viewController?.displaySpinner()
    }

    func present(save result: Result<Storable?, Error>) {
        viewController?.displaySaveResult(save: result)
    }

    func presentRoutingToTitle() {
        viewController?.displayRoutingToTitle()
    }
}
