////
//  HomeRouter.swift
//  Noty
//
//  Created by Youssef Jdidi on 12/2/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol HomeRouterProtocol {
  func set(viewController: HomeViewControllerProtocol?)
  func route(to scene: HomeRouter.Scene)
}

class HomeRouter: NSObject, HomeRouterProtocol {

    // MARK: DI
    weak var viewController: HomeViewControllerProtocol?
    private let rootNavigator: RootNavigatorProtocol
    private let homeStoryboard: Storyboard
    private let alertsStoryboard: Storyboard

    func set(viewController: HomeViewControllerProtocol?) {
        self.viewController = viewController
    }

    init(
        rootNavigator: RootNavigatorProtocol,
        homeStoryboard: Storyboard,
        alertsStoryboard: Storyboard
    ) {
        self.rootNavigator = rootNavigator
        self.homeStoryboard = homeStoryboard
        self.alertsStoryboard = alertsStoryboard
    }
}

// MARK: Routing logic
extension HomeRouter {

    enum Scene {
        case titleAlert(text: String)
    }

    func route(to scene: HomeRouter.Scene) {
        switch scene {
        case .titleAlert(let text):
            guard let vc = alertsStoryboard.viewController(identifier: AlertsStoryboardId.title) as? TitleAlertViewController else { assertionFailure(); return }
            vc.set(text: text)
            viewController?.present(vc, animated: true, completion: nil)
        }
    }
}
