//
//  LanguagePresenter.swift
//  Noty
//
//  Created by Youssef Jdidi on 14/2/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol LanguagePresenterProtocol {
    func set(viewController: LanguageViewControllerProtocol?)

    // add the functions that are called from interactor
    func handle(error: Error)
    func presentSavingLocale()
}

class LanguagePresenter: LanguagePresenterProtocol {

    // MARK: DI
    weak var viewController: LanguageViewControllerProtocol?

    func set(viewController: LanguageViewControllerProtocol?) {
        self.viewController = viewController
    }
}

// MARK: Methods
extension  LanguagePresenter {

    func handle(error: Error) {
        viewController?.display(error: error)
    }

    func presentSavingLocale() {
        viewController?.displaySavingLocale()
    }
}
