//
//  LanguageViewController.swift
//  Noty
//
//  Created by Youssef Jdidi on 14/2/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit
import Speech
import FlagKit

protocol LanguageViewControllerProtocol: class, UIViewControllerRouting {
    func set(interactor: LanguageInteractorProtocol)
    func set(router: LanguageRouterProtocol)

    // add the functions that are called from the presenter
    func display(error: Error)
    func displaySavingLocale()
}

class LanguageViewController: UIViewController, LanguageViewControllerProtocol {

    // MARK: DI
    var interactor: LanguageInteractorProtocol?
    var router: LanguageRouterProtocol?

    func set(interactor: LanguageInteractorProtocol) {
        self.interactor = interactor
    }

    func set(router: LanguageRouterProtocol) {
        self.router = router
    }

    // MARK: Outlets
    @IBOutlet weak var languagePickerView: UIPickerView! {
        didSet {
            languagePickerView.delegate = self
            languagePickerView.dataSource = self
        }
    }

    // MARK: Properties
    private lazy var supportedLanguages: [Locale] = Array(SFSpeechRecognizer.supportedLocales()).sorted { lhs, rhs -> Bool in
        return Locale.autoupdatingCurrent.localizedString(forIdentifier: lhs.identifier)! < Locale.autoupdatingCurrent.localizedString(forIdentifier: rhs.identifier)!
    }

    // MARK: Lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        displayDeviceLanguage()
    }

    // MARK: Actions
    @IBAction func confirmButtonClicked(_ sender: Any) {
        let locale = supportedLanguages[languagePickerView.selectedRow(inComponent: 0)]
        interactor?.saveLanguage(with: locale)
    }
}

// MARK: Methods
extension LanguageViewController {

    func display(error: Error) {}

    func displayDeviceLanguage() {
        if let index = supportedLanguages.firstIndex(where: { locale -> Bool in
            return locale.identifier == NSLocale.preferredLanguages.first
        }) {
            languagePickerView.selectRow(index, inComponent: 0, animated: true)
        }
    }

    func displaySavingLocale() {
        router?.route(to: .permission)
    }
}

// MARK: PickerView delegate and DataSource
extension LanguageViewController: UIPickerViewDelegate, UIPickerViewDataSource {
    func numberOfComponents(in pickerView: UIPickerView) -> Int {
        return 1
    }

    func pickerView(_ pickerView: UIPickerView, numberOfRowsInComponent component: Int) -> Int {
        return supportedLanguages.count
    }

    func pickerView(_ pickerView: UIPickerView, viewForRow row: Int, forComponent component: Int, reusing view: UIView?) -> UIView {
        let locale = supportedLanguages[row]
        let label = UILabel()
        label.font = UIFont.systemFont(ofSize: 14)
        label.text = Locale.current.localizedString(forIdentifier: locale.identifier)?.uppercased()
        label.textAlignment = .left

        let imageView = UIImageView()
        imageView.contentMode = .scaleAspectFit
        if let region = locale.regionCode, let flag = Flag(countryCode: region) {
            imageView.image = flag.image(style: .roundedRect)
        }

        let horizontalStackView = UIStackView(arrangedSubviews: [label, imageView])
        horizontalStackView.axis = .horizontal
        return horizontalStackView
    }

    func pickerView(_ pickerView: UIPickerView, widthForComponent component: Int) -> CGFloat {
        return languagePickerView.frame.width - 30
    }
}
