//
//  LanguageInteractor.swift
//  Noty
//
//  Created by Youssef Jdidi on 14/2/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol LanguageInteractorProtocol {
    func saveLanguage(with locale: Locale)
}

class LanguageInteractor: LanguageInteractorProtocol {

    // MARK: DI
    var presenter: LanguagePresenterProtocol
    var userDefaultsManager: UserDefaultsManagerProtocol

    init(
        presenter: LanguagePresenterProtocol,
        userDefaultsManager: UserDefaultsManagerProtocol
    ) {
        self.presenter = presenter
        self.userDefaultsManager = userDefaultsManager
    }

    // MARK: Methods
    func saveLanguage(with locale: Locale) {
        userDefaultsManager.selectedLanguage = locale
        presenter.presentSavingLocale()
    }
}
