disabled_rules: # rule identifiers to exclude from running
  - nesting
  - multiple_closures_with_trailing_closure
  - operator_whitespace
  - identifier_name
  - todo
  - discouraged_optional_collection
  - implicitly_unwrapped_optional
  - trailing_whitespace
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - closure_spacing
  - number_separator
opt_in_rules: # some rules are only opt-in
  - array_init
  - collection_alignment
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - for_where
  #- function_bdy_lenght
  - function_parameter_count
  - identical_operands
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_random
  - let_var_whitespace
  - modifier_order
  - multiline_arguments
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - opening_brace
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_unit_test
  - prohibited_super_call
  - protocol_property_accessors_order
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - statement_position
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_import
  #- unused_private_declaration
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - xct_specific_matcher
included: # paths to include during linting. `--path` is ignored if present.
  - Noty
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly. Give warning only for force casting

line_length:
  warning: 300
  error: 400
ignores_comments: true

force_try:
severity: warning

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 800

large_tuple:
  warning: 3
  error: 4

type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
reporter: "xcode"
