////
//  SplashScreenRouter.swift
//  Noty
//
//  Created by Youssef Jdidi on 11/2/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol SplashScreenRouterProtocol {
  func set(viewController: SplashScreenViewControllerProtocol?)
  func route(to scene: SplashScreenRouter.Scene)
}

class SplashScreenRouter: NSObject, SplashScreenRouterProtocol {

    // MARK: DI
    weak var viewController: SplashScreenViewControllerProtocol?
    private let rootNavigator: RootNavigatorProtocol
    private let onBoardingStoryboard: Storyboard
    private let homeStoryboard: Storyboard

    func set(viewController: SplashScreenViewControllerProtocol?) {
        self.viewController = viewController
    }

    init(
        rootNavigator: RootNavigatorProtocol,
        onBoardingStoryboard: Storyboard,
        homeStoryboard: Storyboard
    ) {
        self.rootNavigator = rootNavigator
        self.onBoardingStoryboard = onBoardingStoryboard
        self.homeStoryboard = homeStoryboard
    }
}

// MARK: Routing logic
extension SplashScreenRouter {

    enum Scene {
        case onBoarding
        case home
    }

    func route(to scene: SplashScreenRouter.Scene) {
        switch scene {
        case .onBoarding:
            guard let vc = onBoardingStoryboard.initial() as? UINavigationController else { return }
            viewController?.present(vc, animated: true, completion: nil)
        case .home:
            guard let vc = homeStoryboard.initial() as? HomeNavigationController else { return }
            viewController?.present(vc, animated: true, completion: nil)
        }
    }
}
