////
//  NotysRouter.swift
//  Noty
//
//  Created by Youssef Jdidi on 8/3/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol NotysRouterProtocol {
  func set(viewController: NotysViewControllerProtocol?)
  func route(to scene: NotysRouter.Scene)
}

class NotysRouter: NSObject, NotysRouterProtocol {

    //MARK: DI
    weak var viewController: NotysViewControllerProtocol?
    private let rootNavigator: RootNavigatorProtocol
    private let homeStoryboard: Storyboard

    func set(viewController: NotysViewControllerProtocol?) {
        self.viewController = viewController
    }

    init(
        rootNavigator: RootNavigatorProtocol,
        homeStoryboard: Storyboard
    ) {
        self.rootNavigator = rootNavigator
        self.homeStoryboard = homeStoryboard
    }
}

// MARK: Routing logic
extension NotysRouter {

    enum Scene {
        case destination1
    }

    func route(to scene: NotysRouter.Scene) {
        switch scene {
        case .destination1:
            /// TODO: Implement routing
            break
        }
    }
}

