//
//  NotysViewController.swift
//  Noty
//
//  Created by Youssef Jdidi on 8/3/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol NotysViewControllerProtocol: class, UIViewControllerRouting {
    func set(interactor: NotysInteractorProtocol)
    func set(router: NotysRouterProtocol)
    func set(tableViewUtils: NotysTableViewUtilsProtocol)

    // add the functions that are called from the presenter
    func display(error: Error)
    func display(notes: [NoteModel])
}

class NotysViewController: UIViewController, NotysViewControllerProtocol {

    // MARK: DI
    var interactor: NotysInteractorProtocol?
    var router: NotysRouterProtocol?
    var tableViewUtils: NotysTableViewUtilsProtocol?

    func set(interactor: NotysInteractorProtocol) {
        self.interactor = interactor
    }

    func set(router: NotysRouterProtocol) {
        self.router = router
    }

    func set(tableViewUtils: NotysTableViewUtilsProtocol) {
        self.tableViewUtils = tableViewUtils
    }

    // MARK: Outlets
    @IBOutlet weak var tableView: UITableView!

    // MARK: Properties

    // MARK: Lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        setupTableView()
        showSpinner()
        interactor?.fetchNotes()
    }

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        router?.route(to: .tuto)
    }

    // MARK: Actions

}

// MARK: Methods
extension NotysViewController {

    func display(error: Error) {}

    func display(notes: [NoteModel]) {
        hideSpinner()
        notes.count > 0 ? tableViewUtils?.set(data: notes) : configureEmptyView()
        tableView.reloadData()
    }
}

// MARK: Private Methods
private extension NotysViewController {
    func setupTableView() {
        tableView.delegate = tableViewUtils
        tableView.dataSource = tableViewUtils
        tableView.register(UINib(resource: R.nib.noteCell), forCellReuseIdentifier: R.nib.noteCell.identifier)
    }
}

// MARK: Empty dataSource Methods
extension NotysViewController: EmptyBackgroundViewDelegate {
    func configureEmptyView() {
        let view = EmptyBackgroundView(frame: tableView.bounds)
        view.delegate = self
        tableView.backgroundView = view
        tableView.separatorStyle = .none
    }

    func tapNewNote() {}
}
