//
//  SettingsInteractor.swift
//  Noty
//
//  Created by Youssef Jdidi on 9/3/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol SettingsInteractorProtocol {
    func prepareConfigDataSource()
    func handleThemeColor()
}

class SettingsInteractor: SettingsInteractorProtocol {

    // MARK: DI
    var presenter: SettingsPresenterProtocol
    var userDefaults: UserDefaultsManagerProtocol

    init(
        presenter: SettingsPresenterProtocol,
        userDefaults: UserDefaultsManagerProtocol
    ) {
        self.presenter = presenter
        self.userDefaults = userDefaults
    }
}

extension SettingsInteractor {
    func prepareConfigDataSource() {
        presenter.present(locale: userDefaults.selectedLanguage)
    }

    func handleThemeColor() {
        presenter.present(new: userDefaults.themeColor)
    }
}
