//
//  SettingsInteractor.swift
//  Noty
//
//  Created by Youssef Jdidi on 9/3/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol SettingsInteractorProtocol {
    // add the functions that are called from the view controller
}

class SettingsInteractor: SettingsInteractorProtocol {

    // MARK: DI
    var presenter: SettingsPresenterProtocol

    init(presenter: SettingsPresenterProtocol) {
        self.presenter = presenter
    }
}
