//
//  WelcomeViewController.swift
//  Noty
//
//  Created by Youssef Jdidi on 12/2/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol WelcomeViewControllerProtocol: class, UIViewControllerRouting {
    func set(interactor: WelcomeInteractorProtocol)
    func set(router: WelcomeRouterProtocol)

    // add the functions that are called from the presenter
    func display(error: Error)
}

class WelcomeViewController: UIViewController, WelcomeViewControllerProtocol {

    // MARK: DI
    var interactor: WelcomeInteractorProtocol?
    var router: WelcomeRouterProtocol?

    func set(interactor: WelcomeInteractorProtocol) {
        self.interactor = interactor
    }

    func set(router: WelcomeRouterProtocol) {
        self.router = router
    }
    
    // MARK: Outlets

    // MARK: Properties

    // MARK: Lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
    }

    // MARK: Actions
    @IBAction func nextButtonClicked(_ sender: Any) {
        router?.route(to: .login)
    }
}

// MARK: Methods
extension WelcomeViewController {

    func display(error: Error) {}
}
