//
//  WelcomePresenter.swift
//  Noty
//
//  Created by Youssef Jdidi on 12/2/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol WelcomePresenterProtocol {
    func set(viewController: WelcomeViewControllerProtocol?)

    // add the functions that are called from interactor
    func handle(error: Error)
}

class WelcomePresenter: WelcomePresenterProtocol {

    // MARK: DI
    weak var viewController: WelcomeViewControllerProtocol?

    func set(viewController: WelcomeViewControllerProtocol?) {
        self.viewController = viewController
    }
}

// MARK: Methods
extension  WelcomePresenter {

    func handle(error: Error) {
        viewController?.display(error: error)
    }
}
