////
//  WelcomeRouter.swift
//  Noty
//
//  Created by Youssef Jdidi on 12/2/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol WelcomeRouterProtocol {
  func set(viewController: WelcomeViewControllerProtocol?)
  func route(to scene: WelcomeRouter.Scene)
}

class WelcomeRouter: NSObject, WelcomeRouterProtocol {

    // MARK: DI
    weak var viewController: WelcomeViewControllerProtocol?
    private let rootNavigator: RootNavigatorProtocol
    private let homeStoryboard: Storyboard
    private let onBoardingStoryboard: Storyboard

    func set(viewController: WelcomeViewControllerProtocol?) {
        self.viewController = viewController
    }

    init(
        rootNavigator: RootNavigatorProtocol,
        homeStoryboard: Storyboard,
        onBoardingStoryboard: Storyboard
    ) {
        self.rootNavigator = rootNavigator
        self.homeStoryboard = homeStoryboard
        self.onBoardingStoryboard = onBoardingStoryboard
    }
}

// MARK: Routing logic
extension WelcomeRouter {

    enum Scene {
        case home
        case permission
        case language
        case login
    }

    func route(to scene: WelcomeRouter.Scene) {
        switch scene {
        case .home:
            guard let homeVC = homeStoryboard.initial() as? UINavigationController else { return }
            viewController?.present(homeVC, animated: true, completion: nil)
        case .permission:
            guard let permissionVC = onBoardingStoryboard.viewController(identifier: OnBoardingStoryboardId.permission) as? PermissionViewController else { return }
            viewController?.show(permissionVC, sender: nil)
        case .language:
            guard let languageVC = onBoardingStoryboard.viewController(identifier: OnBoardingStoryboardId.language) as? LanguageViewController else { return }
            viewController?.show(languageVC, sender: nil)
        case .login:
            guard let loginVC = onBoardingStoryboard.viewController(identifier: OnBoardingStoryboardId.login) as? LoginViewController else { return }
            viewController?.show(loginVC, sender: nil)
        }
    }
}
