//
//  ConfirmPresenter.swift
//  Noty
//
//  Created by Youssef Jdidi on 15/2/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol ConfirmPresenterProtocol {
    func set(viewController: ConfirmViewControllerProtocol?)

    // add the functions that are called from interactor
    func handle(error: Error)
    func present(confirmText: NSMutableAttributedString)
    func present(tryOtherMail: NSMutableAttributedString)
    func present(actionSheet: UIAlertController)
}

class ConfirmPresenter: ConfirmPresenterProtocol {

    // MARK: DI
    weak var viewController: ConfirmViewControllerProtocol?

    func set(viewController: ConfirmViewControllerProtocol?) {
        self.viewController = viewController
    }
}

// MARK: Methods
extension  ConfirmPresenter {

    func handle(error: Error) {
        viewController?.display(error: error)
    }

    func present(confirmText: NSMutableAttributedString) {
        viewController?.display(confirmText: confirmText)
    }

    func present(tryOtherMail: NSMutableAttributedString) {
        viewController?.display(tryOtherMail: tryOtherMail)
    }

    func present(actionSheet: UIAlertController) {
        viewController?.display(actionSheet: actionSheet)
    }
}
