//
//  DateAlertPresenter.swift
//  Noty
//
//  Created by Youssef Jdidi on 20/3/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol DateAlertPresenterProtocol {
    func set(viewController: DateAlertViewControllerProtocol?)

    func present(date: Date, year: String, dateText: String)
    func present(date: String, year: String)
    func present(theme color: UIColor)
}

class DateAlertPresenter: DateAlertPresenterProtocol {

    // MARK: DI
    weak var viewController: DateAlertViewControllerProtocol?

    func set(viewController: DateAlertViewControllerProtocol?) {
        self.viewController = viewController
    }
}

// MARK: Methods
extension  DateAlertPresenter {
    func present(date: Date, year: String, dateText: String) {
        viewController?.display(date: date, year: year, dateText: dateText)
    }

    func present(date: String, year: String) {
        viewController?.display(date: date, year: year)
    }

    func present(theme color: UIColor) {
        viewController?.display(theme: color)
    }
}
