//
//  DateAlertViewController.swift
//  Noty
//
//  Created by Youssef Jdidi on 20/3/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol DateAlertViewControllerProtocol: class, UIViewControllerRouting {
    func set(interactor: DateAlertInteractorProtocol)
    func set(router: DateAlertRouterProtocol)
    func set(note: NoteModel)
    func set(delegate: DidSaveReminderDelegate?)

    // add the functions that are called from the presenter
    func display(date: Date, year: String, dateText: String)
    func display(date: String, year: String)
    func display(theme color: UIColor)
}

class DateAlertViewController: UIViewController, DateAlertViewControllerProtocol {

    // MARK: DI
    var interactor: DateAlertInteractorProtocol?
    var router: DateAlertRouterProtocol?

    func set(interactor: DateAlertInteractorProtocol) {
        self.interactor = interactor
    }

    func set(router: DateAlertRouterProtocol) {
        self.router = router
    }

    func set(note: NoteModel) {
        self.note = note
    }

    func set(delegate: DidSaveReminderDelegate?) {
        self.delegate = delegate
    }

    // MARK: Outlets
    @IBOutlet weak var datePicker: UIDatePicker! {
        didSet {
            datePicker.addTarget(self, action: #selector(datePickerValueChanged), for: .valueChanged)
        }
    }
    @IBOutlet weak var yearLabel: UILabel!
    @IBOutlet weak var dateLabel: UILabel!
    @IBOutlet weak var containerView: RoundedView! {
        didSet {
            containerView.layer.cornerRadius = 25
        }
    }
    @IBOutlet weak var labelsView: UIView!
    
    // MARK: Properties
    var note: NoteModel?
    weak var delegate: DidSaveReminderDelegate?

    // MARK: Lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        interactor?.handleViewDidLoad()
    }

    // MARK: Actions
    @IBAction func okClicked(_ sender: Any) {
        guard let note = note else { return }
        router?.route(to: .time(date: datePicker.date, note: note, from: delegate))
    }

    @IBAction func cancelClicked(_ sender: Any) {
        dismiss(animated: true, completion: nil)
    }
}

// MARK: Methods
extension DateAlertViewController {

    func display(date: Date, year: String, dateText: String) {
        datePicker.minimumDate = date
        yearLabel.text = year
        dateLabel.text = dateText
    }

    func display(date: String, year: String) {
        DispatchQueue.main.async {[weak self] in
            guard let self = self else { return }
            self.dateLabel.text = date
            self.yearLabel.text = year
        }
    }

    func display(theme color: UIColor) {
        self.labelsView.backgroundColor = color
    }

    @objc func datePickerValueChanged() {
        interactor?.convertDate(date: datePicker.date)
    }
}
