//
//  ThemeAlertPresenter.swift
//  Noty
//
//  Created by Youssef Jdidi on 27/3/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol ThemeAlertPresenterProtocol {
    func set(viewController: ThemeAlertViewControllerProtocol?)

    // add the functions that are called from interactor
    func handle(error: Error)
}

class ThemeAlertPresenter: ThemeAlertPresenterProtocol {

    // MARK: DI
    weak var viewController: ThemeAlertViewControllerProtocol?

    func set(viewController: ThemeAlertViewControllerProtocol?) {
        self.viewController = viewController
    }
}

// MARK: Methods
extension  ThemeAlertPresenter {

    func handle(error: Error) {
        viewController?.display(error: error)
    }
}
