//
//  ThemeAlertViewController.swift
//  Noty
//
//  Created by Youssef Jdidi on 27/3/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol ThemeAlertViewControllerProtocol: class, UIViewControllerRouting {
    func set(interactor: ThemeAlertInteractorProtocol)
    func set(router: ThemeAlertRouterProtocol)

    // add the functions that are called from the presenter
    func display(error: Error)
}

class ThemeAlertViewController: UIViewController, ThemeAlertViewControllerProtocol {

    // MARK: DI
    var interactor: ThemeAlertInteractorProtocol?
    var router: ThemeAlertRouterProtocol?

    func set(interactor: ThemeAlertInteractorProtocol) {
        self.interactor = interactor
    }

    func set(router: ThemeAlertRouterProtocol) {
        self.router = router
    }
    
    // MARK: Outlets
    @IBOutlet weak var containerView: RoundedView!

    // MARK: Properties

    // MARK: Lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        let colorPicker = ColorPicker()
        addSubSwiftUIView(colorPicker, to: view)
    }

    // MARK: Actions

}

// MARK: Methods
extension ThemeAlertViewController {

    func display(error: Error) {}
}
