//
//  ThemeAlertViewController.swift
//  Noty
//
//  Created by Youssef Jdidi on 27/3/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol ThemeAlertViewControllerProtocol: class, UIViewControllerRouting {
    func set(userDefaults: UserDefaultsManagerProtocol)
}

class ThemeAlertViewController: UIViewController, ThemeAlertViewControllerProtocol, WillReceiveNewColor {

    // MARK: DI
    func set(userDefaults: UserDefaultsManagerProtocol) {
        self.userDefaults = userDefaults
    }
    
    // MARK: Outlets
    @IBOutlet weak var containerView: RoundedView!

    // MARK: Properties
    var userDefaults: UserDefaultsManagerProtocol?
    var choosenColor: UIColor?

    // MARK: Lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
        observeColorChange()
    }

    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        guard let color = self.choosenColor else { return }
        self.userDefaults?.themeColor = color
    }

    // MARK: Private Methods
    private func observeColorChange() {
        handleNewColorReceived {[weak self] color in
            guard let self = self else { return }
            self.choosenColor = color
        }
    }
}

// MARK: Methods
extension ThemeAlertViewController {

    private func setupView() {
        guard let currentColor = userDefaults?.themeColor.rgba else { return }
        let currentRGB = RGB(r: currentColor.red, g: currentColor.green, b: currentColor.blue)
        let colorPicker = ColorPicker(rgbColour: currentRGB)
        addSubSwiftUIView(colorPicker, to: view)
    }
}
