////
//  ThemeAlertRouter.swift
//  Noty
//
//  Created by Youssef Jdidi on 27/3/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol ThemeAlertRouterProtocol {
  func set(viewController: ThemeAlertViewControllerProtocol?)
  func route(to scene: ThemeAlertRouter.Scene)
}

class ThemeAlertRouter: NSObject, ThemeAlertRouterProtocol {

    //MARK: DI
    weak var viewController: ThemeAlertViewControllerProtocol?
    private let rootNavigator: RootNavigatorProtocol
    private let alertsStoryboard: Storyboard

    func set(viewController: ThemeAlertViewControllerProtocol?) {
        self.viewController = viewController
    }

    init(
        rootNavigator: RootNavigatorProtocol,
        alertsStoryboard: Storyboard
    ) {
        self.rootNavigator = rootNavigator
        self.alertsStoryboard = alertsStoryboard
    }
}

// MARK: Routing logic
extension ThemeAlertRouter {

    enum Scene {
        case destination1
    }

    func route(to scene: ThemeAlertRouter.Scene) {
        switch scene {
        case .destination1:
            /// TODO: Implement routing
            break
        }
    }
}

