//
//  ThemeAlertInteractor.swift
//  Noty
//
//  Created by Youssef Jdidi on 27/3/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol ThemeAlertInteractorProtocol {
    // add the functions that are called from the view controller
}

class ThemeAlertInteractor: ThemeAlertInteractorProtocol {

    // MARK: DI
    var presenter: ThemeAlertPresenterProtocol

    init(presenter: ThemeAlertPresenterProtocol) {
        self.presenter = presenter
    }
}
