////
//  TutorialRouter.swift
//  Noty
//
//  Created by Youssef Jdidi on 16/3/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol TutorialRouterProtocol {
  func set(viewController: TutorialViewControllerProtocol?)
  func route(to scene: TutorialRouter.Scene)
}

class TutorialRouter: NSObject, TutorialRouterProtocol {

    // MARK: DI
    weak var viewController: TutorialViewControllerProtocol?
    private let rootNavigator: RootNavigatorProtocol
    private let homeStoryboard: Storyboard

    func set(viewController: TutorialViewControllerProtocol?) {
        self.viewController = viewController
    }

    init(
        rootNavigator: RootNavigatorProtocol,
        homeStoryboard: Storyboard
    ) {
        self.rootNavigator = rootNavigator
        self.homeStoryboard = homeStoryboard
    }
}

// MARK: Routing logic
extension TutorialRouter {

    enum Scene {
        case destination1
    }

    func route(to scene: TutorialRouter.Scene) {
        switch scene {
        case .destination1:
            /// TODO: Implement routing
            break
        }
    }
}

