////
//  PermissionRouter.swift
//  Noty
//
//  Created by Youssef Jdidi on 12/2/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol PermissionRouterProtocol {
  func set(viewController: PermissionViewControllerProtocol?)
  func route(to scene: PermissionRouter.Scene)
}

class PermissionRouter: NSObject, PermissionRouterProtocol {

    // MARK: DI
    weak var viewController: PermissionViewControllerProtocol?
    private let rootNavigator: RootNavigatorProtocol
    private let homeStoryboard: Storyboard

    func set(viewController: PermissionViewControllerProtocol?) {
        self.viewController = viewController
    }

    init(
        rootNavigator: RootNavigatorProtocol,
        homeStoryboard: Storyboard
    ) {
        self.rootNavigator = rootNavigator
        self.homeStoryboard = homeStoryboard
    }
}

// MARK: Routing logic
extension PermissionRouter {

    enum Scene {
        case home
    }

    func route(to scene: PermissionRouter.Scene) {
        switch scene {
        case .home:
            guard let homeVC = homeStoryboard.initial() as? UINavigationController else { return }
            viewController?.present(homeVC, animated: true, completion: nil)
        }
    }
}
