//
//  TimeAlertViewController.swift
//  Noty
//
//  Created by Youssef Jdidi on 20/3/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol TimeAlertViewControllerProtocol: class, UIViewControllerRouting {
    func set(interactor: TimeAlertInteractorProtocol)
    func set(router: TimeAlertRouterProtocol)
    func set(date: Date)

    // add the functions that are called from the presenter
    func display(time: String, isAm: Bool)
}

class TimeAlertViewController: UIViewController, TimeAlertViewControllerProtocol {

    // MARK: DI
    var interactor: TimeAlertInteractorProtocol?
    var router: TimeAlertRouterProtocol?

    func set(interactor: TimeAlertInteractorProtocol) {
        self.interactor = interactor
    }

    func set(router: TimeAlertRouterProtocol) {
        self.router = router
    }

    func set(date: Date) {
        self.date = date
    }

    // MARK: Outlets
    @IBOutlet weak var timePicker: UIDatePicker! {
        didSet {
            timePicker.addTarget(self, action: #selector(timePickerValueChanged), for: .valueChanged)
        }
    }
    @IBOutlet weak var containerView: RoundedView! {
        didSet {
            containerView.layer.cornerRadius = 25
        }
    }
    @IBOutlet weak var timeLabel: UILabel!
    @IBOutlet weak var amLabel: UILabel!
    @IBOutlet weak var pmLabel: UILabel!

    // MARK: Properties
    var date: Date?

    // MARK: Lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        checkDate()
    }

    // MARK: Actions
    @IBAction func okClicked(_ sender: Any) {
    }

    @IBAction func cancelClicked(_ sender: Any) {
        let date = presentingViewController
        date?.view.isHidden = true
        self.dismiss(animated: true) {
            date?.dismiss(animated: true, completion: nil)
        }
    }
}

// MARK: Methods
extension TimeAlertViewController {

    func display(time: String, isAm: Bool) {
        DispatchQueue.main.async {[weak self] in
            guard let self = self else { return }
            self.amLabel.textColor = isAm ? UIColor.white.withAlphaComponent(1) : UIColor.white.withAlphaComponent(0.5)
            self.pmLabel.textColor = isAm ? UIColor.white.withAlphaComponent(0.5) :
                UIColor.white.withAlphaComponent(1)
            self.timeLabel.text = time
        }
    }

    private func checkDate() {
        guard let date = self.date else { return }
        timePicker.minimumDate = Calendar.current.isDateInToday(date) ? date : nil
        interactor?.convertDate(date: date)
    }

    @objc private func timePickerValueChanged() {
        interactor?.convertDate(date: timePicker.date)
    }
}
