//
//  TimeAlertInteractor.swift
//  Noty
//
//  Created by Youssef Jdidi on 20/3/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol TimeAlertInteractorProtocol {
    func convertDate(date: Date)
}

class TimeAlertInteractor: TimeAlertInteractorProtocol {

    // MARK: DI
    var presenter: TimeAlertPresenterProtocol
    var dateFormatter: DateFormatterProtocol

    init(
        presenter: TimeAlertPresenterProtocol,
        dateFormatter: DateFormatterProtocol
        ) {
        self.presenter = presenter
        self.dateFormatter = dateFormatter
    }
}

extension TimeAlertInteractor {
    func convertDate(date: Date) {
        presenter.present(time: dateFormatter.get(date: date, in: "h:mm a"))
    }
}
